<a href="https://colab.research.google.com/github/MukundcMenon/Learning_AI/blob/main/Neural_Network_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

# Bare Python Way to get the output of a neuron
layer_output = []

for weight,bias in zip(weights,biases):
  neuron_output = 0
  for input,input_weight in zip(inputs,weight):
      neuron_output += input * input_weight
  layer_output.append(neuron_output+bias)

print(layer_output)

# Numpy Way of getting an output of a neuron
layer_output = np.dot(weights,inputs) + biases
print(layer_output)

In [ ]:
# Taking inputs as batches

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]
layer_output = np.dot(X, np.array(weights).T) + biases
layer_output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [ ]:

'''
Initialise the weights and biases
The initialisation should be within a certain numerical range
The lower the range, the better the chance to reduce exploding
Generally the range chosen is between -1 to 1
'''
class DenseLayer():
  def __init__(self,n_inputs, n_neurons):
    self.weights = 0.1 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self,inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU():
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

"""
To implement the Activation_Softmax class
The exponential should not end up in an exploding problem
Hence inidividual numbers of the array are subtracted from thne largest value from the array
Then put into e^x and then normalised
This results in a value of the normalisation between 0 and 1
"""

class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis =1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

' \nX = [[1, 2, 3, 2.5],\n     [2.0, 5.0, -1.0, 2.0],\n     [-1.5, 2.7, 3.3, -0.8]]\n\nlayer1 = DenseLayer(4,5)\nlayer2 = DenseLayer(5,2)\n\nlayer1.forward(X)\nprint(layer1.output)\nlayer2.forward(layer1.output)\nprint(layer2.output)\n\n'

In [ ]:
# Dataset: A Spiral dataset

def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y


X, y = spiral_data(100, 3)
"""
The above is a dataset containing X and Y axis of a spiral dataset
Since it is only two axis, the number of features is 2
Hence the n_inputs = 2
"""

'\nThe above is a dataset containing X and Y axis of a spiral dataset\nSince it is only two axis, the number of features is 2\nHence the n_inputs = 2\n'

In [ ]:
dense1 = DenseLayer(2,3)
activation1 = Activation_ReLU()

dense2 = DenseLayer(3,3) # Treating this as an Output layer, and the data has 3 Classes
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output)

[[0.33333333 0.33333333 0.33333333]
 [0.33333394 0.33330825 0.33335781]
 [0.33338024 0.33323415 0.33338561]
 [0.33333558 0.33324088 0.33342354]
 [0.33333656 0.33320023 0.33346322]
 [0.33336726 0.33317989 0.33345284]
 [0.33333791 0.33314417 0.33351793]
 [0.33333905 0.33309653 0.33356442]
 [0.33333939 0.33308205 0.33357856]
 [0.33334043 0.33303859 0.33362098]
 [0.33334086 0.33302041 0.33363872]
 [0.33334215 0.33296595 0.33369189]
 [0.33334287 0.33293556 0.33372157]
 [0.33334391 0.33289148 0.33376461]
 [0.33334475 0.33285572 0.33379953]
 [0.33334528 0.33283304 0.33382168]
 [0.33334557 0.33282085 0.33383358]
 [0.33336407 0.33340979 0.33322614]
 [0.33334563 0.33281799 0.33383638]
 [0.33334842 0.33269829 0.33395329]
 [0.33335612 0.33300646 0.33363742]
 [0.33337147 0.33343482 0.33319371]
 [0.33336643 0.33319728 0.33343629]
 [0.33339043 0.33382517 0.3327844 ]
 [0.33339127 0.33383238 0.33277635]
 [0.3334498  0.33377016 0.33278003]
 [0.33339474 0.33386246 0.3327428 ]
 [0.33338869 0.33377985 0.33